In [1]:
#importing dependencies
import pandas as pd
import recom_class as recon

In [2]:
#loading the datasets
song_ID = pd.read_csv('songUserID.csv')
song_Data = pd.read_csv('songData.csv')

In [3]:
song_ID.head()

                                    user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1

In [4]:
song_Data.head()

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster Pussy cat,2003
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteillä,Karkkiautomaatti,1995
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006
3,SOBNYVR12A8C13558C,Si Vos Querés,De Culo,Yerba Brava,2003
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0

In [5]:
#creating new dataframe by merging the given two dataframes
Songs = pd.merge(song_ID, song_Data.drop_duplicates(['song_id']), on='song_id', how='left')
Songs.head()

,user_id,song_id,listen_count,title,release,artist_name,year
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999

In [6]:
#merging the features 'title' and 'artist' to create a new feature 'song' for concise handling of the dataset
Songs['Song'] = Songs['title']+'-'+Songs['artist_name']
Songs.head()

,user_id,song_id,listen_count,title,release,artist_name,year,Song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0,The Cove-Jack Johnson
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976,Entre Dos Aguas-Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007,Stronger-Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005,Constellations-Jack Johnson
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999,Learn To Fly-Foo Fighters

In [7]:
#limiting training entries to 50000 for faster prediction (more the input, greater is the time to predict)
Songs = Songs.head(50000)

In [8]:
#aggregating the listen count of individual songs into a single value
Grouped_count = Songs.groupby(['Song']).agg({'listen_count':'count'}).reset_index()
Grouped_count.head(10)

                                                Song  listen_count
0  #!*@ You Tonight [Featuring R. Kelly] (Explici...             1
1                             #40-DAVE MATTHEWS BAND             7
2                                  & Down-Boys Noize            13
3                            ' Cello Song-Nick Drake             3
4                          '97 Bonnie & Clyde-Eminem             5
5                      'Round Midnight-Amy Winehouse             4
6                        'Round Midnight-Miles Davis             7
7               'Til We Die (Album Version)-Slipknot             5
8                'Till I Collapse-Eminem / Nate Dogg            29
9              (Anaesthesia) Pulling Teath-Metallica             3

In [9]:
#finding total listen count of all the songs in the dataframe
Sum = Grouped_count['listen_count'].sum()

#creating new feature percentile
Grouped_count['Percentage'] = (Grouped_count['listen_count'] / Sum ) * 100
print("\n         SHOWING THE MOST POPULAR SONGS IN THE DATASET\n")
Grouped_count.sort_values(['listen_count', 'Song'], ascending=[0,1])

         SHOWING THE MOST POPULAR SONGS IN THE DATASET

,Song,listen_count,Percentage
6682,Sehr kosmisch-Harmonia,204,0.408
8509,Undo-Björk,182,0.364
1936,Dog Days Are Over (Radio Edit)-Florence + The ...,173,0.346
9253,You're The One-Dwight Yoakam,169,0.338
6348,Revelry-Kings Of Leon,166,0.332
...,...,...,...
9290,Your Time Has Come-Audioslave,1,0.002
9300,Zebra (full-length/album version)-John Butler ...,1,0.002
9311,clouding-Four Tet,1,0.002
9312,high fives-Four Tet,1,0.002
9321,the Love Song-K-OS,1,0.002

In [10]:
#creating a instance to find similar items
similarItems = recon.Similar_Items_Recommender()
similarItems.construct(Songs, 'user_id', 'Song')

In [11]:
print("\n\n\n\n==================================================================")
name=input("|| ENTER A SONG NAME: || ")
print("==================================================================")
similarItems.get_similar_items([name])

==================================================================

|| ENTER A SONG NAME: ||  Bones-Radiohead

==================================================================

Number of UNIQUE songs in the dataframe : 9325
SIMILAR songs found : 745

==================================================================
 Rank                                    Song    Similarity Score
    1                  Planet Telex-Radiohead            0.750000
    2 Punchdrunk Lovesick Singalong-Radiohead            0.500000
    3                 The Trickster-Radiohead            0.500000
    4                Prove Yourself-Radiohead            0.428571
    5                Talk Show Host-Radiohead            0.428571
    6                          Just-Radiohead            0.416667
    7       Exit Music (For A Film)-Radiohead            0.416667
    8                       Ripcord-Radiohead            0.375000
    9                          Sulk-Radiohead            0.285714
   10        You Wanted A Hit-LCD Soundsystem            0.285714
==================================================================